source :rubygems

# Specify your gem's dependencies in capitan.gemspec
# gemspec

gem 'sinatra'
gem 'activesupport'
gem 'activerecord'
gem 'sqlite3'

gem 'mustache'
gem 'engineyard'
gem 'redis-namespace'
gem 'faraday', '0.8.0.rc2'
gem 'faraday_middleware'

# gem "json"
# gem "pony"
# gem "tlsmail"
# gem "open4"

group :test, :development do
  gem 'rspec'
  gem 'rack-test'
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'capybara'

  gem 'fakeweb'
  gem 'vcr', "2.0.0.rc1"
  gem 'launchy'
  
  gem 'ruby-debug19'
end
