#!/usr/bin/env ruby

require 'net/http'
require 'uri'

job_name = "topic_action"
body = {  "name" => job_name, 
          "url" => "JobUrl", 
          "build" => {
            "number" => 1, 
            "phase" => "STARTED", 
            "status" => "FAILED", 
            "url" => "job/project/5", 
            "fullUrl" => "http://ci.jenkins.org/job/project/5",
            "parameters" => {
              "branch" => "master"
            }
        }}

uri = URI.parse('http://capitan-challengepost.herokuapp.com/notifications/jenkins')
# uri = URI.parse('http://localhost:3123/notifications/jenkins')
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new(uri.request_uri)
request.set_form_data(body)
response = http.request(request)

puts response


# {"{\"name\":\"topic_action\",\"url\":\"job/topic_action/\",\"build\":{\"full_url\":\"http://ci.berman.challengepost.com/job/topic_action/364/\",\"number\":364,\"phase\":\"STARTED\",\"url\":\"job/topic_action/364/\"}}"=>nil, "controller"=>"notifications", "action"=>"create", "id"=>"jenkins"}
# {"{\"name\":\"topic_action\",\"url\":\"job/topic_action/\",\"build\":{\"full_url\":\"http://ci.berman.challengepost.com/job/topic_action/364/\",\"number\":364,\"phase\":\"COMPLETED\",\"status\":\"SUCCESS\",\"url\":\"job/topic_action/364/\"}}"=>nil, "controller"=>"notifications", "action"=>"create", "id"=>"jenkins"}
# {"{\"name\":\"topic_action\",\"url\":\"job/topic_action/\",\"build\":{\"full_url\":\"http://ci.berman.challengepost.com/job/topic_action/364/\",\"number\":364,\"phase\":\"FINISHED\",\"status\":\"SUCCESS\",\"url\":\"job/topic_action/364/\"}}"=>nil, "controller"=>"notifications", "action"=>"create", "id"=>"jenkins"}
# {"name"=>"topic_action", "url"=>"JobUrl", "build"=>"[\"parameters\", {\"branch\"=>\"master\"}]", "controller"=>"notifications", "action"=>"create", "id"=>"jenkins"}